### ISSUE TITLE
Roll over 

### ISSUE THREAD

**Issue by kwprod** [kwprod/STO-2015#1]
Roll over sur les titres des documents : faire comme pour les boutons/ picto de téléchargement
Roll over picto theme powerpoint = changer « thmx »par « theme ppt »

**Comment by gabdavid** [comment]
Roll over prend uniquement les extensions

**Comment by kw-dev** [comment]
![capture d ecran 2015-06-15 a 15 08 36](https://cloud.githubusercontent.com/assets/2630041/8160495/6d1cb326-1370-11e5-93cc-c9f193b950e6.jpeg)
C'est fait
