### ISSUE TITLE
catégorie & version anglaise

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#13]
Le bug persiste. On ne peut pas faire apparaître les catégories en même temps en FR et en EN

**Comment by gabdavid** [comment]
D'une manière générale, chaque modification sur la version française, la catégorie de la version anglaise disparaît

**Comment by kw-dev** [comment]
c'est corrigé. 
Si le problème persiste, veuillez m'indiquer le noms des pages (c'est le cas pour certaines pages)
