### ISSUE TITLE
Catégorie PAPETERIE

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#15]
Supprimer le menu déroulant Corporate et tous regrouper dans Pays (Chine et Suisse compris)

**Comment by kw-dev** [comment]
c'est fait

**Comment by gabdavid** [comment]
Il y a un bug lorsque je reclasse les documents, ils apparaissent bien dans la liste pays mais reste présent dans la liste corporate.

**Comment by gabdavid** [comment]
Apparemment, la liste des pays est limité à 10, alors que dans la catégorie "papeterie", nous devons en voir 13.

**Comment by kw-dev** [comment]
c'est corrigé.
l'affichage tous les menu déroulant limitée à 16
