### ISSUE TITLE
Titre téléchargement dans menu prinicpal

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#16]
grossir x2 corp de texte et mettre en gras

**Comment by kw-dev** [comment]
c'est fait.

**Comment by gabdavid** [comment]
Merci Sergey. Il faut une dernière modifs sur ce point.
Homogénéiser la taille et la graisse des polices de "téléchargement" et de "charte communication".
Du coup, il faut descendre d'une taille de police "téléchargement" et augmenter d'une taille "charte communication". Et faut graisser les deux titres.

**Comment by kw-dev** [comment]
c'est fait

**Comment by gabdavid** [comment]
ok, peux tu encore augmenter la taille de Police de "charte communication", il faut le mettre de la même taille que "téléchargement"

**Comment by kw-dev** [comment]
ok, c'est fait.
