### ISSUE TITLE
différence d'espacement dans les picto de téléchargement

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#17]
![image](https://cloud.githubusercontent.com/assets/12844127/8278430/7c92704c-18cb-11e5-96f4-8ea92d743111.png)

il y a une différence d'espacement quand on passe de 5 à 6 picto

**Comment by kw-dev** [comment]
j'ai été obligé de aligner les pictos à gauche. 
Si non, sur le responsive il y a trop de problèmes..
