### ISSUE TITLE
Mettre un "robot.txt" pour éviter l'indexation.

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#21]
Voici le commentaire du client :
"si possible, dans le script du site d'un "robot.txt" pour éviter les indexations par les moteurs de recherche du site... pour nous le plus mauvais référencement de ce site est le mieux "

Avant toutes actions, m'évaluer le temps à réaliser cela.

**Comment by kw-dev** [comment]
c'est fait.
