### ISSUE TITLE
programmer pour le que le login/Mdp se bloque après 3 essais infructueux. 

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#22]
Est-ce possible avec le module présent ?

**Comment by kw-dev** [comment]
oui, j'ai installé le nouveau module "Limit Attempts".
![capture d ecran 2015-07-08 a 12 39 49](https://cloud.githubusercontent.com/assets/2630041/8568517/89d33980-256e-11e5-8ee6-d83662c825ea.jpeg)
