### ISSUE TITLE
En fonction de l'adresse IP, est-ce que le site pourrait s'ouvrir par défaut en français ou en anglais ? 

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#24]
en fonction de l'adresse IP, est-ce que le site pourrait s'ouvrir par défaut en français ou en anglais ?

**Comment by kw-dev** [comment]
oui, par le module WPML : Redirection selon le pays de l'utilisateur. (pour l'instant désactivé)
![capture d ecran 2015-07-08 a 12 20 44](https://cloud.githubusercontent.com/assets/2630041/8568182/dc3e9e92-256b-11e5-85eb-840af436dffc.jpeg)

**Comment by gabdavid** [comment]
OK, super. Peux-tu le mettre ?

**Comment by kw-dev** [comment]
ok, c'est déjà fait.
