### ISSUE TITLE
menu prinicipal

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#25]
il faudrait  sur la barre outil un indicateur (coloré ou autre) qui signal sur quel onglet on est (même si c'est marqué en titre et que le site est très simple)

![image](https://cloud.githubusercontent.com/assets/12844127/8380246/fb8cd944-1c24-11e5-84cc-816814e18b43.png)
![image](https://cloud.githubusercontent.com/assets/12844127/8380250/01677590-1c25-11e5-8cb6-2f5fea17f245.png)

**Comment by kw-dev** [comment]
Ok, j'ai souligné le titre active.
![capture d ecran 2015-07-08 a 12 08 34](https://cloud.githubusercontent.com/assets/2630041/8567974/1a203bdc-256a-11e5-82eb-8a9b9cbe3b44.jpeg)
