### ISSUE TITLE
Compatibilité chrome

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#30]
![image](https://cloud.githubusercontent.com/assets/12844127/8571943/e8a0d1f0-2589-11e5-9554-05be523afa85.png)
- Les menus déroulant ne sont pas identiques à ceux de chrome (couleur de bouton)
- Pas de catégorie souslignée (ici "logo")

**Comment by gabdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/12844127/8699350/3e699b28-2b05-11e5-8e9a-cbc3b01de307.png)

**Comment by gabdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/12844127/8699406/901917aa-2b05-11e5-8fe9-041019d1a52b.png)

**Comment by kw-dev** [comment]
catégorie soulignée - corrigé, OK!
