### ISSUE TITLE
cat PAPETERIE : calage 

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#31]
![image](https://cloud.githubusercontent.com/assets/12844127/8615824/a13e1c0a-26f6-11e5-9f24-bf7677d725d1.png)
![image](https://cloud.githubusercontent.com/assets/12844127/8615828/aca83e04-26f6-11e5-9e4a-32f714425f3e.png)

**Comment by kw-dev** [comment]
...le même problème comme dans la cat. "marquages", résolu!
