### ISSUE TITLE
Cat MARQUAGE : calage

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#32]
![image](https://cloud.githubusercontent.com/assets/12844127/8616053/6f0ebd46-26f8-11e5-9224-6214230ed16f.png)
![image](https://cloud.githubusercontent.com/assets/12844127/8616064/778ca5fa-26f8-11e5-8158-a2a69d3d2c9b.png)

**Comment by gabdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/12844127/8616091/ac47c3ec-26f8-11e5-8fd0-4471edb96827.png)

**Comment by kw-dev** [comment]
J'ai ajouté une ligne de séparation entre chaque ligne, le problème est résolu, ok!
