### ISSUE TITLE
backoffice - titre et chargement des paquets

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#34]
Lors du chargement d'un document d'un paquet, peut-on faire apparaitre le titre doc et dans le titre du paquet par défaut ?

**Comment by kw-dev** [comment]
oui, j'ai ajouté le titre doc dans le titre du paquet : 
![capture d ecran 2015-07-13 a 11 53 25](https://cloud.githubusercontent.com/assets/2630041/8647168/cd4eda30-2955-11e5-8cf7-3f2c0184d7b8.jpeg)
