### ISSUE TITLE
Catégorie EDITION : titre des filtres

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#5]
Titre premier menu déroulant : En Fr : Format  -  En En : Format
Titre deuxième menu déroulant : En Fr : Version -  En En : Template items du menu déroulant : Anglaise, Française, Universelle

**Comment by gabdavid** [comment]
ordre : 
- A3
- A4
- 240x240
- A5
  -110x210

et mettre un petit "x" dans 240x240 et 110x210

**Comment by kw-dev** [comment]
c'est fait
