### ISSUE TITLE
création filtre image corporate dans catégorie STAND et EDITION

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#7]
Mettre ce nouveau filtre après les filtres déjà mis en place.

Titre : En Fr : Image Coporate  -  En En : Corporate Pictures
Liste des items : 
1 - Connaissance
2 - Performance
3 - Satisfaction
4 - Bien-être

Remplacer N’importe lequel par “Tous”

**Comment by kw-dev** [comment]
c'est fait
