### ISSUE TITLE
Catégorie MARQUAGE: titre des filtres

### ISSUE THREAD

**Issue by gabdavid** [kwprod/STO-2015#9]
Titre : En Fr : Analyseur  -  En En : System
Liste des analyseurs 

Titre : En Fr : Certifications  -  En En : Certifications
Changer les noms des items : 
Directive européenne = Directive 98/79/CE
Label ISO 14001 = ISO 14001
G-med = ISO 13485

Titre : En Fr : Sociétés du Groupe  -  En En : Stago’s Companies

**Comment by kw-dev** [comment]
c'est fait

**Comment by gabdavid** [comment]
Changer les noms des items n'est pas réalisé : 
Directive européenne = Directive 98/79/CE - Eng : EU directive
Label ISO 14001 = ISO 14001
G-med = ISO 13485

**Comment by gabdavid** [comment]
Numéro d'ordre indiqué ( )
(3) Grouper CompactCT Systems + Compact_STA dans "STA Compact"

(2) Grouper Evolution_STA + STA_STA-R dans "STA_STA-R"

(1) Grouper STA R Max + STA Compact Max dans "Génération Max"

(4) STA Satellite OK

(6) Small & old systems devient "Archive"

(5) Tcoag_DMax... devient "Gamme Tcoag"

**Comment by kw-dev** [comment]
c'est fait.
J'ai déjà effectué la modification les noms des items!!
En effet, il faut re-assigner le nouveau tag pour chaque document! (menu derullant / back-office)
![capture d ecran 2015-06-17 a 14 17 30](https://cloud.githubusercontent.com/assets/2630041/8206632/ab654954-14fb-11e5-8cc5-84a32934b94f.jpeg)

**Comment by gabdavid** [comment]
ok, c noté
